In [1]:
import pandas as pd

file_path = r"D:\MBA\Project data\PET_IMPORTS_full.csv"

df = pd.read_csv(file_path)

print("Dataset loaded successfully!")
print("Rows:", len(df))
print("Columns:", len(df.columns))

df.head()

Dataset loaded successfully!
Rows: 972117
Columns: 13

,series_id,name,units,frequency,source,geography,geography2,start,end,last_updated,geoset_id,date,value
0,PET_IMPORTS.REG_CA-RS_KY-ALL.M,Imports of all grades of crude oil from Canada...,thousand barrels,NaN,"EIA, U.S. Energy Information Administration",CAN,USA-KY,200905,202607,2026-09-29T19:32:50-04:00,PET_IMPORTS.RS_KY-ALL.M,202607,62
1,PET_IMPORTS.REG_CA-RS_KY-ALL.M,Imports of all grades of crude oil from Canada...,thousand barrels,NaN,"EIA, U.S. Energy Information Administration",CAN,USA-KY,200905,202607,2026-09-29T19:32:50-04:00,PET_IMPORTS.RS_KY-ALL.M,202206,247
2,PET_IMPORTS.REG_CA-RS_KY-ALL.M,Imports of all grades of crude oil from Canada...,thousand barrels,NaN,"EIA, U.S. Energy Information Administration",CAN,USA-KY,200905,202607,2026-09-29T19:32:50-04:00,PET_IMPORTS.RS_KY-ALL.M,201909,4357
3,PET_IMPORTS.REG_CA-RS_KY-ALL.M,Imports of all grades of crude oil from Canada...,thousand barrels,NaN,"EIA, U.S. Energy Information Administration",CAN,USA-KY,200905,202607,2026-09-29T19:32:50-04:00,PET_IMPORTS.RS_KY-ALL.M,201908,4710
4,PET_IMPORTS.REG_CA-RS_KY-ALL.M,Imports of all grades of crude oil from Canada...,thousand barrels,NaN,"EIA, U.S. Energy Information Administration",CAN,USA-KY,200905,202607,2026-09-29T19:32:50-04:00,PET_IMPORTS.RS_KY-ALL.M,201907,7562

In [2]:
print("COLUMN NAMES")
print(df.columns.tolist())

print("\nDATA TYPES")
print(df.dtypes)

print("\nDATASET SHAPE")
print(df.shape)

print("\nMISSING VALUES")
print(df.isnull().sum())

print("\nUNIQUE VALUES — IMPORTANT COLUMNS")

for col in ["geography", "geography2", "units", "frequency"]:
    if col in df.columns:
        print(f"\n{col}:")
        print(df[col].dropna().unique()[:20])

COLUMN NAMES
['series_id', 'name', 'units', 'frequency', 'source', 'geography', 'geography2', 'start', 'end', 'last_updated', 'geoset_id', 'date', 'value']

DATA TYPES
series_id           str
name                str
units               str
frequency       float64
source              str
geography           str
geography2          str
start             int64
end               int64
last_updated        str
geoset_id           str
date              int64
value             int64
dtype: object

DATASET SHAPE
(972117, 13)

MISSING VALUES
series_id            0
name                 0
units                0
frequency       972117
source               0
geography            0
geography2           0
start                0
end                  0
last_updated         0
geoset_id            0
date                 0
value                0
dtype: int64

UNIQUE VALUES — IMPORTANT COLUMNS

geography:
<StringArray>
[                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        'CAN',
                                                                                                                                                                                                                                                                                                                                                                     'ABW+ANT+ARG+ATG+BHS+BLZ+BMU+BOL+BRA+BRB+CHL+COL+CRI+CUW+DOM+ECU+FWI+GTM+GUF+GUY+JAM+MEX+MTQ+NIC+PAN+PER+PRI+PRY+SLV+SUR+TTO+URY+VEN+VIR',
                                                                                                                                                                                                                                                                                                                        'ALB+AUT+BEL+BGR+BIH+CHE+CSK+CYP+CZE+DDR+DEU+DEUW+DNK+ESP+EST+FIN+FRA+FRO+GBR+GIB+GRC+HRV+HUN+IRL+ISL+ITA+LTU+LUX+LVA+MKD+MLT+MNE+NLD+NOR+POL+PRT+ROU+SCG+SRB+SVK+SVN+SWE+TUR+XKS+YUG',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         'WLD',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         'VEN',
 'ABW+AGO+ALB+ANT+ARG+ATG+AUS+AUT+AZE+BEL+BEN+BGR+BHR+BHS+BIH+BLR+BLZ+BMU+BOL+BRA+BRB+BRN+CAN+CHE+CHL+CHN+CIV+CMR+COD+COL+COM+CRI+CUW+CYP+CZE+DEU+DNK+DOM+ECU+EGY+ESP+EST+FIN+FRA+FWI+GBR+GEO+GHA+GIB+GIN+GRC+GTM+GUF+GUY+HKG+HRV+HUN+IDN+IND+IRL+ISR+ITA+JAM+JOR+JPN+KAZ+KGZ+KOR+LBR+LKA+LTU+LVA+MAR+MEX+MHL+MLT+MOZ+MRT+MTQ+MYS+NIC+NLD+NOR+NZL+OMN+PAK+PAN+PER+PHL+PNG+POL+PRI+PRT+PRY+QAT+ROU+RUS+SDN+SEN+SGP+SLV+SRB+SSD+SUN+SUR+SVK+SWE+SYR+TCD+TGO+THA+TKM+TTO+TUN+TUR+TWN+UKR+URY+UZB+VIR+VNM+YEM+ZAF',
                                                                                                                                                                                                                                                                                                                                                                                                                                                             'ARE+COG+DZA+GAB+GNQ+IRN+IRQ+KWT+LBY+NGA+SAU+VEN',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         'GBR',
                                                                                                                                                                                                                                                                         'AGO+BDI+BEN+BFA+BWA+CAF+CIV+CMR+COD+COG+COM+CPV+DJI+DZA+EGY+ERI+ESH+ETH+GAB+GHA+GIN+GMB+GNB+GNQ+KEN+LBR+LBY+LSO+MAR+MDG+MLI+MOZ+MRT+MUS+MWI+NAM+NER+NGA+REU+RWA+SDN+SEN+SHN+SLE+SOM+SSD+STP+SWZ+SYC+TCD+TGO+TUN+TZA+UGA+ZAF+ZMB+ZWE',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         'PAN',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         'MEX',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         'LBY',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         'NGA',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         'COL',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         'ECU',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         'GUY',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         'GHA',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         'BRA',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         'DZA',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         'AGO']
Length: 20, dtype: str

geography2:
<StringArray>
['USA-KY', 'USA-MI', 'USA-UT', 'USA-OK',    'USA', 'USA-AL', 'USA-WA',
 'USA-LA', 'USA-NJ', 'USA-IN', 'USA-AK', 'USA-CO', 'USA-CA', 'USA-TX',
 'USA-MO', 'USA-MS', 'USA-KS', 'USA-WY', 'USA-MT', 'USA-OH']
Length: 20, dtype: str

units:
<StringArray>
['thousand barrels']
Length: 1, dtype: str

frequency:
[]

In [3]:
print("MISSING VALUES BY COLUMN")
print(df.isnull().sum().to_string())

print("\n" + "="*60)
print("NUMBER OF UNIQUE VALUES")
print("="*60)

for col in df.columns:
    print(f"{col}: {df[col].nunique()}")

print("\n" + "="*60)
print("DATE RANGE / SAMPLE")
print("="*60)

print("Minimum date:", df["date"].min())
print("Maximum date:", df["date"].max())
print("Sample dates:", df["date"].drop_duplicates().sort_values().head(10).tolist())

print("\n" + "="*60)
print("UNITS")
print("="*60)
print(df["units"].value_counts(dropna=False))

print("\n" + "="*60)
print("FREQUENCY")
print("="*60)
print(df["frequency"].value_counts(dropna=False))

print("\n" + "="*60)
print("SAMPLE SERIES NAMES")
print("="*60)
print(df[["series_id", "name"]].drop_duplicates().head(20).to_string(index=False))

MISSING VALUES BY COLUMN
series_id            0
name                 0
units                0
frequency       972117
source               0
geography            0
geography2           0
start                0
end                  0
last_updated         0
geoset_id            0
date                 0
value                0

============================================================
NUMBER OF UNIQUE VALUES
============================================================
series_id: 46140
name: 46140
units: 1
frequency: 0
source: 1
geography: 70
geography2: 49
start: 227
end: 228
last_updated: 1589
geoset_id: 4315
date: 228
value: 40522

============================================================
DATE RANGE / SAMPLE
============================================================
Minimum date: 2009
Maximum date: 202607
Sample dates: [2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018]

============================================================
UNITS
============================================================
units
thousand barrels    972117
Name: count, dtype: int64

============================================================
FREQUENCY
============================================================
frequency
NaN    972117
Name: count, dtype: int64

============================================================
SAMPLE SERIES NAMES
============================================================
                       series_id                                                                                                                          name
  PET_IMPORTS.REG_CA-RS_KY-ALL.M                                    Imports of all grades of crude oil from Canada (Region) to refineries in Kentucky, Monthly
  PET_IMPORTS.REG_CA-RS_MI-ALL.M                                    Imports of all grades of crude oil from Canada (Region) to refineries in Michigan, Monthly
  PET_IMPORTS.REG_CA-RS_UT-ALL.M                                        Imports of all grades of crude oil from Canada (Region) to refineries in Utah, Monthly
  PET_IMPORTS.REG_CA-RS_OK-ALL.M                                    Imports of all grades of crude oil from Canada (Region) to refineries in Oklahoma, Monthly
     PET_IMPORTS.REG_CA-US-ALL.M                                           Imports of all grades of crude oil from Canada (Region) to Total U.S. (US), Monthly
  PET_IMPORTS.REG_CA-RS_AL-ALL.M                                     Imports of all grades of crude oil from Canada (Region) to refineries in Alabama, Monthly
  PET_IMPORTS.REG_CA-RS_WA-ALL.M                                  Imports of all grades of crude oil from Canada (Region) to refineries in Washington, Monthly
 PET_IMPORTS.REG_OA-RF_517-ALL.M     Imports of all grades of crude oil from Other Americas to VALERO REFG NEW ORLEANS LLC / SAINT CHARLES / LA (517), Monthly
  PET_IMPORTS.REG_CA-RS_NJ-ALL.M                                  Imports of all grades of crude oil from Canada (Region) to refineries in New Jersey, Monthly
PET_IMPORTS.REG_EU-PT_2001-ALL.M                                                    Imports of all grades of crude oil from Europe to Morgan City, LA, Monthly
  PET_IMPORTS.REG_CA-RS_IN-ALL.M                                     Imports of all grades of crude oil from Canada (Region) to refineries in Indiana, Monthly
  PET_IMPORTS.REG_CA-RS_AK-ALL.M                                      Imports of all grades of crude oil from Canada (Region) to refineries in Alaska, Monthly
  PET_IMPORTS.REG_CA-RS_CO-ALL.M                                    Imports of all grades of crude oil from Canada (Region) to refineries in Colorado, Monthly
 PET_IMPORTS.REG_OA-RF_120-ALL.M                          Imports of all grades of crude oil from Other Americas to CHEVRON USA / RICHMOND / CA (120), Monthly
 PET_IMPORTS.REG_OA-RF_163-ALL.M         Imports of all grades of crude oil from Other Americas to EXXONMOBIL REFINING & SPLY CO / BAYTOWN / TX (163), Monthly
 PET_IMPORTS.WORLD-PT_4503-ALL.M                                                        Imports of all grades of crude oil from World to St Louis, MO, Monthly
  PET_IMPORTS.WORLD-RF_125-ALL.M                                 Imports of all grades of crude oil from World to CHEVRON USA / PASCAGOULA / MS (125), Monthly
  PET_IMPORTS.WORLD-RF_168-ALL.M                       Imports of all grades of crude oil from World to CVR REFINING CVL LLC / COFFEYVILLE / KS (168), Monthly
  PET_IMPORTS.WORLD-RF_191-ALL.M Imports of all grades of crude oil from World to VALERO REFINING CO CALIFORNIA / WILMINGTON ASPHALT PLANT / CA (191), Monthly
 PET_IMPORTS.WORLD-PT_5505-ALL.M                                                           Imports of all grades of crude oil from World to Tulsa, OK, Monthly

In [4]:
print("=" * 70)
print("DESTINATION GEOGRAPHIES")
print("=" * 70)

print(df["geography2"].value_counts().to_string())

print("\n" + "=" * 70)
print("SERIES TYPE PATTERNS")
print("=" * 70)

print("\nRefinery-level series:")
print(
    df[df["series_id"].str.contains("-RF_", na=False)]
    [["series_id", "name", "geography", "geography2"]]
    .drop_duplicates()
    .head(20)
    .to_string(index=False)
)

print("\nPoint/terminal-level series:")
print(
    df[df["series_id"].str.contains("-PT_", na=False)]
    [["series_id", "name", "geography", "geography2"]]
    .drop_duplicates()
    .head(20)
    .to_string(index=False)
)

print("\nUSA-level series:")
print(
    df[df["geography2"] == "USA"]
    [["series_id", "name", "geography", "geography2"]]
    .drop_duplicates()
    .head(20)
    .to_string(index=False)
)

======================================================================
DESTINATION GEOGRAPHIES
======================================================================
geography2
USA-TX                                                                                                                           139032
USA-CA                                                                                                                           102310
USA-LA                                                                                                                            87424
USA-WA                                                                                                                            52770
USA-NJ                                                                                                                            43734
USA-PA                                                                                                                            42509
USA-IL                                                                                                                            39051
USA-AL+USA-AR+USA-LA+USA-MS+USA-NM+USA-TX                                                                                         34646
USA-AK+USA-AZ+USA-CA+USA-HI+USA-NV+USA-OR+USA-WA                                                                                  34314
USA-MT                                                                                                                            32100
USA-CT+USA-DC+USA-DE+USA-FL+USA-GA+USA-MA+USA-MD+USA-ME+USA-NC+USA-NH+USA-NJ+USA-NY+USA-PA+USA-RI+USA-SC+USA-VA+USA-VT+USA-WV     29227
USA                                                                                                                               27199
USA-MS                                                                                                                            25789
USA-DE                                                                                                                            25033
USA-MN                                                                                                                            23464
USA-OH                                                                                                                            21793
USA-HI                                                                                                                            20738
USA-OK                                                                                                                            20221
USA-AL                                                                                                                            18113
USA-MI                                                                                                                            15486
USA-WY                                                                                                                            13960
USA-IA+USA-IL+USA-IN+USA-KS+USA-KY+USA-MI+USA-MN+USA-MO+USA-ND+USA-NE+USA-OH+USA-OK+USA-SD+USA-TN+USA-WI                          12479
USA-ND                                                                                                                            12064
USA-CO                                                                                                                            11876
USA-KS                                                                                                                            10092
USA-IN                                                                                                                             9960
USA-CO+USA-ID+USA-MT+USA-UT+USA-WY                                                                                                 9660
USA-UT                                                                                                                             9316
USA-WI                                                                                                                             7908
USA-NY                                                                                                                             6874
USA-MO                                                                                                                             6732
USA-KY                                                                                                                             5823
VIR                                                                                                                                5388
USA-ID                                                                                                                             2992
USA-AK                                                                                                                             2770
PRI+VIR                                                                                                                            2694
USA-AR                                                                                                                             1680
USA-VA                                                                                                                             1100
USA-NM                                                                                                                             1032
USA-TN                                                                                                                              696
USA-NE                                                                                                                              572
USA-GA                                                                                                                              320
USA-OR                                                                                                                              296
USA-IA                                                                                                                              264
USA-FL                                                                                                                              240
USA-MD                                                                                                                              184
USA-MA                                                                                                                              128
USA-AZ                                                                                                                               32
USA-VT                                                                                                                               32

======================================================================
SERIES TYPE PATTERNS
======================================================================

Refinery-level series:
                      series_id                                                                                                                                    name                                                                                                                               geography geography2
PET_IMPORTS.REG_OA-RF_517-ALL.M               Imports of all grades of crude oil from Other Americas to VALERO REFG NEW ORLEANS LLC / SAINT CHARLES / LA (517), Monthly ABW+ANT+ARG+ATG+BHS+BLZ+BMU+BOL+BRA+BRB+CHL+COL+CRI+CUW+DOM+ECU+FWI+GTM+GUF+GUY+JAM+MEX+MTQ+NIC+PAN+PER+PRI+PRY+SLV+SUR+TTO+URY+VEN+VIR     USA-LA
PET_IMPORTS.REG_OA-RF_120-ALL.M                                    Imports of all grades of crude oil from Other Americas to CHEVRON USA / RICHMOND / CA (120), Monthly ABW+ANT+ARG+ATG+BHS+BLZ+BMU+BOL+BRA+BRB+CHL+COL+CRI+CUW+DOM+ECU+FWI+GTM+GUF+GUY+JAM+MEX+MTQ+NIC+PAN+PER+PRI+PRY+SLV+SUR+TTO+URY+VEN+VIR     USA-CA
PET_IMPORTS.REG_OA-RF_163-ALL.M                   Imports of all grades of crude oil from Other Americas to EXXONMOBIL REFINING & SPLY CO / BAYTOWN / TX (163), Monthly ABW+ANT+ARG+ATG+BHS+BLZ+BMU+BOL+BRA+BRB+CHL+COL+CRI+CUW+DOM+ECU+FWI+GTM+GUF+GUY+JAM+MEX+MTQ+NIC+PAN+PER+PRI+PRY+SLV+SUR+TTO+URY+VEN+VIR     USA-TX
 PET_IMPORTS.WORLD-RF_125-ALL.M                                           Imports of all grades of crude oil from World to CHEVRON USA / PASCAGOULA / MS (125), Monthly                                                                                                                                     WLD     USA-MS
 PET_IMPORTS.WORLD-RF_168-ALL.M                                 Imports of all grades of crude oil from World to CVR REFINING CVL LLC / COFFEYVILLE / KS (168), Monthly                                                                                                                                     WLD     USA-KS
 PET_IMPORTS.WORLD-RF_191-ALL.M           Imports of all grades of crude oil from World to VALERO REFINING CO CALIFORNIA / WILMINGTON ASPHALT PLANT / CA (191), Monthly                                                                                                                                     WLD     USA-CA
 PET_IMPORTS.WORLD-RF_163-ALL.M                            Imports of all grades of crude oil from World to EXXONMOBIL REFINING & SPLY CO / BAYTOWN / TX (163), Monthly                                                                                                                                     WLD     USA-TX
 PET_IMPORTS.WORLD-RF_161-ALL.M                Imports of all grades of crude oil from World to EXXONMOBIL REFINING & SUPPLY / BATON ROUGE REFINERY / LA (161), Monthly                                                                                                                                     WLD     USA-LA
PET_IMPORTS.REG_CA-RF_190-ALL.M                            Imports of all grades of crude oil from Canada (Region) to HUNT REFINING CO / TUSCALOOSA / AL (190), Monthly                                                                                                                                     CAN     USA-AL
PET_IMPORTS.REG_CA-RF_225-ALL.M                 Imports of all grades of crude oil from Canada (Region) to EXXONMOBIL REFINING & SPLY CO / BEAUMONT / TX (225), Monthly                                                                                                                                     CAN     USA-TX
PET_IMPORTS.REG_CA-RF_187-ALL.M               Imports of all grades of crude oil from Canada (Region) to CALUMET MONTANA REFINING LLC / GREAT FALLS / MT (187), Monthly                                                                                                                                     CAN     USA-MT
PET_IMPORTS.REG_CA-RF_223-ALL.M                    Imports of all grades of crude oil from Canada (Region) to PAULSBORO REFINING CO LLC / PAULSBORO / NJ (223), Monthly                                                                                                                                     CAN     USA-NJ
PET_IMPORTS.REG_CA-RF_191-ALL.M Imports of all grades of crude oil from Canada (Region) to VALERO REFINING CO CALIFORNIA / WILMINGTON ASPHALT PLANT / CA (191), Monthly                                                                                                                                     CAN     USA-CA
PET_IMPORTS.REG_CA-RF_203-ALL.M            Imports of all grades of crude oil from Canada (Region) to FLINT HILLS RESOURCES LP / PINE BEND REFINERY / MN (203), Monthly                                                                                                                                     CAN     USA-MN
PET_IMPORTS.REG_CA-RF_227-ALL.M                   Imports of all grades of crude oil from Canada (Region) to EXXONMOBIL REFINING & SPLY CO / JOLIET / IL (227), Monthly                                                                                                                                     CAN     USA-IL
 PET_IMPORTS.WORLD-RF_115-ALL.M                             Imports of all grades of crude oil from World to CHS MCPHERSON REFINERY INC / MCPHERSON / KS (115), Monthly                                                                                                                                     WLD     USA-KS
 PET_IMPORTS.WORLD-RF_162-ALL.M                                Imports of all grades of crude oil from World to PAR MONTANA LLC / BILLINGS REFINERY / MT (162), Monthly                                                                                                                                     WLD     USA-MT
 PET_IMPORTS.WORLD-RF_190-ALL.M                                      Imports of all grades of crude oil from World to HUNT REFINING CO / TUSCALOOSA / AL (190), Monthly                                                                                                                                     WLD     USA-AL
 PET_IMPORTS.WORLD-RF_120-ALL.M                                             Imports of all grades of crude oil from World to CHEVRON USA / RICHMOND / CA (120), Monthly                                                                                                                                     WLD     USA-CA
 PET_IMPORTS.WORLD-RF_116-ALL.M                                                   Imports of all grades of crude oil from World to CHS INC / LAUREL / MT (116), Monthly                                                                                                                                     WLD     USA-MT

Point/terminal-level series:
                       series_id                                                                              name                                                                                                                                                                            geography geography2
PET_IMPORTS.REG_EU-PT_2001-ALL.M        Imports of all grades of crude oil from Europe to Morgan City, LA, Monthly ALB+AUT+BEL+BGR+BIH+CHE+CSK+CYP+CZE+DDR+DEU+DEUW+DNK+ESP+EST+FIN+FRA+FRO+GBR+GIB+GRC+HRV+HUN+IRL+ISL+ITA+LTU+LUX+LVA+MKD+MLT+MNE+NLD+NOR+POL+PRT+ROU+SCG+SRB+SVK+SVN+SWE+TUR+XKS+YUG     USA-LA
 PET_IMPORTS.WORLD-PT_4503-ALL.M            Imports of all grades of crude oil from World to St Louis, MO, Monthly                                                                                                                                                                                  WLD     USA-MO
 PET_IMPORTS.WORLD-PT_5505-ALL.M               Imports of all grades of crude oil from World to Tulsa, OK, Monthly                                                                                                                                                                                  WLD     USA-OK
 PET_IMPORTS.WORLD-PT_5312-ALL.M        Imports of all grades of crude oil from World to Corpus Chris, TX, Monthly                                                                                                                                                                                  WLD     USA-TX
 PET_IMPORTS.WORLD-PT_5301-ALL.M             Imports of all grades of crude oil from World to Houston, TX, Monthly                                                                                                                                                                                  WLD     USA-TX
PET_IMPORTS.REG_EU-PT_1903-ALL.M         Imports of all grades of crude oil from Europe to Pascagoula, MS, Monthly ALB+AUT+BEL+BGR+BIH+CHE+CSK+CYP+CZE+DDR+DEU+DEUW+DNK+ESP+EST+FIN+FRA+FRO+GBR+GIB+GRC+HRV+HUN+IRL+ISL+ITA+LTU+LUX+LVA+MKD+MLT+MNE+NLD+NOR+POL+PRT+ROU+SCG+SRB+SVK+SVN+SWE+TUR+XKS+YUG     USA-MS
 PET_IMPORTS.WORLD-PT_3802-ALL.M          Imports of all grades of crude oil from World to Port Huron, MI, Monthly                                                                                                                                                                                  WLD     USA-MI
 PET_IMPORTS.WORLD-PT_5306-ALL.M          Imports of all grades of crude oil from World to Texas City, TX, Monthly                                                                                                                                                                                  WLD     USA-TX
 PET_IMPORTS.WORLD-PT_3902-ALL.M              Imports of all grades of crude oil from World to Peoria, IL, Monthly                                                                                                                                                                                  WLD     USA-IL
 PET_IMPORTS.WORLD-PT_3901-ALL.M             Imports of all grades of crude oil from World to Chicago, IL, Monthly                                                                                                                                                                                  WLD     USA-IL
 PET_IMPORTS.WORLD-PT_5311-ALL.M            Imports of all grades of crude oil from World to Freeport, TX, Monthly                                                                                                                                                                                  WLD     USA-TX
 PET_IMPORTS.WORLD-PT_1903-ALL.M          Imports of all grades of crude oil from World to Pascagoula, MS, Monthly                                                                                                                                                                                  WLD     USA-MS
 PET_IMPORTS.WORLD-PT_1003-ALL.M              Imports of all grades of crude oil from World to Newark, NJ, Monthly                                                                                                                                                                                  WLD     USA-NJ
 PET_IMPORTS.WORLD-PT_1102-ALL.M             Imports of all grades of crude oil from World to Chester, PA, Monthly                                                                                                                                                                                  WLD     USA-PA
 PET_IMPORTS.WORLD-PT_1901-ALL.M              Imports of all grades of crude oil from World to Mobile, AL, Monthly                                                                                                                                                                                  WLD     USA-AL
 PET_IMPORTS.WORLD-PT_1103-ALL.M          Imports of all grades of crude oil from World to Wilmington, DE, Monthly                                                                                                                                                                                  WLD     USA-DE
 PET_IMPORTS.WORLD-PT_4105-ALL.M     Imports of all grades of crude oil from World to Toledo-Sandusky, OH, Monthly                                                                                                                                                                                  WLD     USA-OH
 PET_IMPORTS.WORLD-PT_0901-ALL.M        Imports of all grades of crude oil from World to Buff-Niag Fl, NY, Monthly                                                                                                                                                                                  WLD     USA-NY
 PET_IMPORTS.WORLD-PT_1101-ALL.M        Imports of all grades of crude oil from World to Philadelphia, PA, Monthly                                                                                                                                                                                  WLD     USA-PA

In [5]:
print("=" * 70)
print("SERIES TYPE COUNTS")
print("=" * 70)

print(
    df["series_id"]
    .str.extract(r"PET_IMPORTS\.([A-Z]+)_")[0]
    .value_counts()
)

print("\n" + "=" * 70)
print("COUNTRY-LEVEL EXAMPLES")
print("=" * 70)

country_examples = (
    df[df["series_id"].str.contains(r"\.CTY_", regex=True, na=False)]
    [["series_id", "name", "geography", "geography2"]]
    .drop_duplicates()
    .head(10)
)

print(country_examples.to_string(index=False))

print("\n" + "=" * 70)
print("REFINERY-LEVEL EXAMPLES")
print("=" * 70)

refinery_examples = (
    df[df["series_id"].str.contains(r"-RF_", regex=True, na=False)]
    [["series_id", "name", "geography", "geography2"]]
    .drop_duplicates()
    .head(10)
)

print(refinery_examples.to_string(index=False))

print("\n" + "=" * 70)
print("POINT / TERMINAL-LEVEL EXAMPLES")
print("=" * 70)

point_examples = (
    df[df["series_id"].str.contains(r"-PT_", regex=True, na=False)]
    [["series_id", "name", "geography", "geography2"]]
    .drop_duplicates()
    .head(10)
)

print(point_examples.to_string(index=False))

======================================================================
SERIES TYPE COUNTS
======================================================================
0
CTY    362169
REG    250023
OPN    200074
Name: count, dtype: int64

======================================================================
COUNTRY-LEVEL EXAMPLES
======================================================================
                       series_id                                                                                                                    name geography geography2
 PET_IMPORTS.CTY_VE-RF_351-ALL.M   Imports of all grades of crude oil from Venezuela to VALERO REFINING CO TEXAS LP / CORPUS CHRISTI / TX (351), Monthly       VEN     USA-TX
     PET_IMPORTS.CTY_VE-US-ALL.M                                           Imports of all grades of crude oil from Venezuela to Total U.S. (US), Monthly       VEN        USA
  PET_IMPORTS.CTY_VE-RS_MS-ALL.M                                 Imports of all grades of crude oil from Venezuela to refineries in Mississippi, Monthly       VEN     USA-MS
PET_IMPORTS.CTY_VE-PT_2001-ALL.M                                           Imports of all grades of crude oil from Venezuela to Morgan City, LA, Monthly       VEN     USA-LA
PET_IMPORTS.CTY_VE-PT_2002-ALL.M                                           Imports of all grades of crude oil from Venezuela to New Orleans, LA, Monthly       VEN     USA-LA
 PET_IMPORTS.CTY_VE-RF_478-ALL.M Imports of all grades of crude oil from Venezuela to CITGO REFINING & CHEMICAL INC / CORPUS CHRISTI / TX (478), Monthly       VEN     USA-TX
  PET_IMPORTS.CTY_VE-RS_LA-ALL.M                                   Imports of all grades of crude oil from Venezuela to refineries in Louisiana, Monthly       VEN     USA-LA
 PET_IMPORTS.CTY_VE-RF_163-ALL.M        Imports of all grades of crude oil from Venezuela to EXXONMOBIL REFINING & SPLY CO / BAYTOWN / TX (163), Monthly       VEN     USA-TX
PET_IMPORTS.CTY_VE-PT_2101-ALL.M                                           Imports of all grades of crude oil from Venezuela to Port Arthur, TX, Monthly       VEN     USA-TX
 PET_IMPORTS.CTY_VE-RF_465-ALL.M   Imports of all grades of crude oil from Venezuela to CITGO PETROLEUM CORP / LAKE CHARLES REFINERY / LA (465), Monthly       VEN     USA-LA

======================================================================
REFINERY-LEVEL EXAMPLES
======================================================================
                      series_id                                                                                                                          name                                                                                                                               geography geography2
PET_IMPORTS.REG_OA-RF_517-ALL.M     Imports of all grades of crude oil from Other Americas to VALERO REFG NEW ORLEANS LLC / SAINT CHARLES / LA (517), Monthly ABW+ANT+ARG+ATG+BHS+BLZ+BMU+BOL+BRA+BRB+CHL+COL+CRI+CUW+DOM+ECU+FWI+GTM+GUF+GUY+JAM+MEX+MTQ+NIC+PAN+PER+PRI+PRY+SLV+SUR+TTO+URY+VEN+VIR     USA-LA
PET_IMPORTS.REG_OA-RF_120-ALL.M                          Imports of all grades of crude oil from Other Americas to CHEVRON USA / RICHMOND / CA (120), Monthly ABW+ANT+ARG+ATG+BHS+BLZ+BMU+BOL+BRA+BRB+CHL+COL+CRI+CUW+DOM+ECU+FWI+GTM+GUF+GUY+JAM+MEX+MTQ+NIC+PAN+PER+PRI+PRY+SLV+SUR+TTO+URY+VEN+VIR     USA-CA
PET_IMPORTS.REG_OA-RF_163-ALL.M         Imports of all grades of crude oil from Other Americas to EXXONMOBIL REFINING & SPLY CO / BAYTOWN / TX (163), Monthly ABW+ANT+ARG+ATG+BHS+BLZ+BMU+BOL+BRA+BRB+CHL+COL+CRI+CUW+DOM+ECU+FWI+GTM+GUF+GUY+JAM+MEX+MTQ+NIC+PAN+PER+PRI+PRY+SLV+SUR+TTO+URY+VEN+VIR     USA-TX
 PET_IMPORTS.WORLD-RF_125-ALL.M                                 Imports of all grades of crude oil from World to CHEVRON USA / PASCAGOULA / MS (125), Monthly                                                                                                                                     WLD     USA-MS
 PET_IMPORTS.WORLD-RF_168-ALL.M                       Imports of all grades of crude oil from World to CVR REFINING CVL LLC / COFFEYVILLE / KS (168), Monthly                                                                                                                                     WLD     USA-KS
 PET_IMPORTS.WORLD-RF_191-ALL.M Imports of all grades of crude oil from World to VALERO REFINING CO CALIFORNIA / WILMINGTON ASPHALT PLANT / CA (191), Monthly                                                                                                                                     WLD     USA-CA
 PET_IMPORTS.WORLD-RF_163-ALL.M                  Imports of all grades of crude oil from World to EXXONMOBIL REFINING & SPLY CO / BAYTOWN / TX (163), Monthly                                                                                                                                     WLD     USA-TX
 PET_IMPORTS.WORLD-RF_161-ALL.M      Imports of all grades of crude oil from World to EXXONMOBIL REFINING & SUPPLY / BATON ROUGE REFINERY / LA (161), Monthly                                                                                                                                     WLD     USA-LA
PET_IMPORTS.REG_CA-RF_190-ALL.M                  Imports of all grades of crude oil from Canada (Region) to HUNT REFINING CO / TUSCALOOSA / AL (190), Monthly                                                                                                                                     CAN     USA-AL
PET_IMPORTS.REG_CA-RF_225-ALL.M       Imports of all grades of crude oil from Canada (Region) to EXXONMOBIL REFINING & SPLY CO / BEAUMONT / TX (225), Monthly                                                                                                                                     CAN     USA-TX

======================================================================
POINT / TERMINAL-LEVEL EXAMPLES
======================================================================
                       series_id                                                                       name                                                                                                                                                                            geography geography2
PET_IMPORTS.REG_EU-PT_2001-ALL.M Imports of all grades of crude oil from Europe to Morgan City, LA, Monthly ALB+AUT+BEL+BGR+BIH+CHE+CSK+CYP+CZE+DDR+DEU+DEUW+DNK+ESP+EST+FIN+FRA+FRO+GBR+GIB+GRC+HRV+HUN+IRL+ISL+ITA+LTU+LUX+LVA+MKD+MLT+MNE+NLD+NOR+POL+PRT+ROU+SCG+SRB+SVK+SVN+SWE+TUR+XKS+YUG     USA-LA
 PET_IMPORTS.WORLD-PT_4503-ALL.M     Imports of all grades of crude oil from World to St Louis, MO, Monthly                                                                                                                                                                                  WLD     USA-MO
 PET_IMPORTS.WORLD-PT_5505-ALL.M        Imports of all grades of crude oil from World to Tulsa, OK, Monthly                                                                                                                                                                                  WLD     USA-OK
 PET_IMPORTS.WORLD-PT_5312-ALL.M Imports of all grades of crude oil from World to Corpus Chris, TX, Monthly                                                                                                                                                                                  WLD     USA-TX
 PET_IMPORTS.WORLD-PT_5301-ALL.M      Imports of all grades of crude oil from World to Houston, TX, Monthly                                                                                                                                                                                  WLD     USA-TX
PET_IMPORTS.REG_EU-PT_1903-ALL.M  Imports of all grades of crude oil from Europe to Pascagoula, MS, Monthly ALB+AUT+BEL+BGR+BIH+CHE+CSK+CYP+CZE+DDR+DEU+DEUW+DNK+ESP+EST+FIN+FRA+FRO+GBR+GIB+GRC+HRV+HUN+IRL+ISL+ITA+LTU+LUX+LVA+MKD+MLT+MNE+NLD+NOR+POL+PRT+ROU+SCG+SRB+SVK+SVN+SWE+TUR+XKS+YUG     USA-MS
 PET_IMPORTS.WORLD-PT_3802-ALL.M   Imports of all grades of crude oil from World to Port Huron, MI, Monthly                                                                                                                                                                                  WLD     USA-MI
 PET_IMPORTS.WORLD-PT_5306-ALL.M   Imports of all grades of crude oil from World to Texas City, TX, Monthly                                                                                                                                                                                  WLD     USA-TX
 PET_IMPORTS.WORLD-PT_3902-ALL.M       Imports of all grades of crude oil from World to Peoria, IL, Monthly                                                                                                                                                                                  WLD     USA-IL
 PET_IMPORTS.WORLD-PT_3901-ALL.M      Imports of all grades of crude oil from World to Chicago, IL, Monthly                                                                                                                                                                                  WLD     USA-IL

In [6]:
import re

# Get unique series definitions
series_df = df[
    ["series_id", "name", "geography", "geography2"]
].drop_duplicates()

# Extract the part between the source geography and crude grade
series_df["destination_code"] = (
    series_df["series_id"]
    .str.extract(r"-([A-Z0-9_]+)-ALL\.M$")[0]
)

print("UNIQUE DESTINATION CODE PATTERNS")
print("=" * 70)

print(
    series_df["destination_code"]
    .value_counts()
    .head(50)
    .to_string()
)

print("\n" + "=" * 70)
print("DESTINATION CODE EXAMPLES")
print("=" * 70)

for pattern in ["US", "RF_", "RS_", "PT_"]:
    print(f"\n--- {pattern} ---")

    temp = series_df[
        series_df["destination_code"].str.startswith(
            pattern,
            na=False
        )
    ]

    print(
        temp[
            ["series_id", "name", "geography", "geography2", "destination_code"]
        ]
        .head(10)
        .to_string(index=False)
    )

UNIQUE DESTINATION CODE PATTERNS
======================================================================
destination_code
US         71
PP_3       62
RP_3       62
RP_5       59
PP_5       59
PS_TX      58
RS_TX      58
RP_1       54
PP_1       54
PS_LA      53
RS_LA      53
PS_CA      52
RS_CA      51
RS_NJ      49
PT_5301    47
PT_2101    46
PS_NJ      45
PS_PA      44
PT_2010    44
PT_5312    43
RS_PA      42
PT_1101    42
RS_WA      41
PS_WA      41
PT_1103    41
PS_DE      41
PT_5311    40
PT_2704    40
PT_2001    39
RS_MS      39
PT_2017    39
RS_DE      39
RF_506     38
RS_HI      38
PT_3201    38
PS_HI      38
PT_2820    38
RF_125     37
PT_1105    37
PT_5306    36
RF_465     36
RF_478     36
PT_2002    36
PT_2004    36
RF_363     36
RF_307     36
RF_161     35
RF_225     35
PT_1901    35
RF_98      35

======================================================================
DESTINATION CODE EXAMPLES
======================================================================

--- US ---
                  series_id                                                                                name                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   geography geography2 destination_code
PET_IMPORTS.REG_CA-US-ALL.M Imports of all grades of crude oil from Canada (Region) to Total U.S. (US), Monthly                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         CAN        USA               US
 PET_IMPORTS.WORLD-US-ALL.M           Imports of all grades of crude oil from World to Total U.S. (US), Monthly                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         WLD        USA               US
PET_IMPORTS.CTY_VE-US-ALL.M       Imports of all grades of crude oil from Venezuela to Total U.S. (US), Monthly                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         VEN        USA               US
PET_IMPORTS.REG_OA-US-ALL.M  Imports of all grades of crude oil from Other Americas to Total U.S. (US), Monthly                                                                                                                                                                                                                                                                                                                                                                     ABW+ANT+ARG+ATG+BHS+BLZ+BMU+BOL+BRA+BRB+CHL+COL+CRI+CUW+DOM+ECU+FWI+GTM+GUF+GUY+JAM+MEX+MTQ+NIC+PAN+PER+PRI+PRY+SLV+SUR+TTO+URY+VEN+VIR        USA               US
PET_IMPORTS.REG_EU-US-ALL.M          Imports of all grades of crude oil from Europe to Total U.S. (US), Monthly                                                                                                                                                                                                                                                                                                                        ALB+AUT+BEL+BGR+BIH+CHE+CSK+CYP+CZE+DDR+DEU+DEUW+DNK+ESP+EST+FIN+FRA+FRO+GBR+GIB+GRC+HRV+HUN+IRL+ISL+ITA+LTU+LUX+LVA+MKD+MLT+MNE+NLD+NOR+POL+PRT+ROU+SCG+SRB+SVK+SVN+SWE+TUR+XKS+YUG        USA               US
PET_IMPORTS.CTY_UK-US-ALL.M  Imports of all grades of crude oil from United Kingdom to Total U.S. (US), Monthly                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         GBR        USA               US
 PET_IMPORTS.OPN_N-US-ALL.M        Imports of all grades of crude oil from Non-OPEC to Total U.S. (US), Monthly ABW+AGO+ALB+ANT+ARG+ATG+AUS+AUT+AZE+BEL+BEN+BGR+BHR+BHS+BIH+BLR+BLZ+BMU+BOL+BRA+BRB+BRN+CAN+CHE+CHL+CHN+CIV+CMR+COD+COL+COM+CRI+CUW+CYP+CZE+DEU+DNK+DOM+ECU+EGY+ESP+EST+FIN+FRA+FWI+GBR+GEO+GHA+GIB+GIN+GRC+GTM+GUF+GUY+HKG+HRV+HUN+IDN+IND+IRL+ISR+ITA+JAM+JOR+JPN+KAZ+KGZ+KOR+LBR+LKA+LTU+LVA+MAR+MEX+MHL+MLT+MOZ+MRT+MTQ+MYS+NIC+NLD+NOR+NZL+OMN+PAK+PAN+PER+PHL+PNG+POL+PRI+PRT+PRY+QAT+ROU+RUS+SDN+SEN+SGP+SLV+SRB+SSD+SUN+SUR+SVK+SWE+SYR+TCD+TGO+THA+TKM+TTO+TUN+TUR+TWN+UKR+URY+UZB+VIR+VNM+YEM+ZAF        USA               US
 PET_IMPORTS.OPN_Y-US-ALL.M            Imports of all grades of crude oil from OPEC to Total U.S. (US), Monthly                                                                                                                                                                                                                                                                                                                                                                                                                                                             ARE+COG+DZA+GAB+GNQ+IRN+IRQ+KWT+LBY+NGA+SAU+VEN        USA               US
PET_IMPORTS.REG_AF-US-ALL.M          Imports of all grades of crude oil from Africa to Total U.S. (US), Monthly                                                                                                                                                                                                                                                                         AGO+BDI+BEN+BFA+BWA+CAF+CIV+CMR+COD+COG+COM+CPV+DJI+DZA+EGY+ERI+ESH+ETH+GAB+GHA+GIN+GMB+GNB+GNQ+KEN+LBR+LBY+LSO+MAR+MDG+MLI+MOZ+MRT+MUS+MWI+NAM+NER+NGA+REU+RWA+SDN+SEN+SHN+SLE+SOM+SSD+STP+SWZ+SYC+TCD+TGO+TUN+TZA+UGA+ZAF+ZMB+ZWE        USA               US
PET_IMPORTS.CTY_PM-US-ALL.M          Imports of all grades of crude oil from Panama to Total U.S. (US), Monthly                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         PAN        USA               US

--- RF_ ---
                      series_id                                                                                                                          name                                                                                                                               geography geography2 destination_code
PET_IMPORTS.REG_OA-RF_517-ALL.M     Imports of all grades of crude oil from Other Americas to VALERO REFG NEW ORLEANS LLC / SAINT CHARLES / LA (517), Monthly ABW+ANT+ARG+ATG+BHS+BLZ+BMU+BOL+BRA+BRB+CHL+COL+CRI+CUW+DOM+ECU+FWI+GTM+GUF+GUY+JAM+MEX+MTQ+NIC+PAN+PER+PRI+PRY+SLV+SUR+TTO+URY+VEN+VIR     USA-LA           RF_517
PET_IMPORTS.REG_OA-RF_120-ALL.M                          Imports of all grades of crude oil from Other Americas to CHEVRON USA / RICHMOND / CA (120), Monthly ABW+ANT+ARG+ATG+BHS+BLZ+BMU+BOL+BRA+BRB+CHL+COL+CRI+CUW+DOM+ECU+FWI+GTM+GUF+GUY+JAM+MEX+MTQ+NIC+PAN+PER+PRI+PRY+SLV+SUR+TTO+URY+VEN+VIR     USA-CA           RF_120
PET_IMPORTS.REG_OA-RF_163-ALL.M         Imports of all grades of crude oil from Other Americas to EXXONMOBIL REFINING & SPLY CO / BAYTOWN / TX (163), Monthly ABW+ANT+ARG+ATG+BHS+BLZ+BMU+BOL+BRA+BRB+CHL+COL+CRI+CUW+DOM+ECU+FWI+GTM+GUF+GUY+JAM+MEX+MTQ+NIC+PAN+PER+PRI+PRY+SLV+SUR+TTO+URY+VEN+VIR     USA-TX           RF_163
 PET_IMPORTS.WORLD-RF_125-ALL.M                                 Imports of all grades of crude oil from World to CHEVRON USA / PASCAGOULA / MS (125), Monthly                                                                                                                                     WLD     USA-MS           RF_125
 PET_IMPORTS.WORLD-RF_168-ALL.M                       Imports of all grades of crude oil from World to CVR REFINING CVL LLC / COFFEYVILLE / KS (168), Monthly                                                                                                                                     WLD     USA-KS           RF_168
 PET_IMPORTS.WORLD-RF_191-ALL.M Imports of all grades of crude oil from World to VALERO REFINING CO CALIFORNIA / WILMINGTON ASPHALT PLANT / CA (191), Monthly                                                                                                                                     WLD     USA-CA           RF_191
 PET_IMPORTS.WORLD-RF_163-ALL.M                  Imports of all grades of crude oil from World to EXXONMOBIL REFINING & SPLY CO / BAYTOWN / TX (163), Monthly                                                                                                                                     WLD     USA-TX           RF_163
 PET_IMPORTS.WORLD-RF_161-ALL.M      Imports of all grades of crude oil from World to EXXONMOBIL REFINING & SUPPLY / BATON ROUGE REFINERY / LA (161), Monthly                                                                                                                                     WLD     USA-LA           RF_161
PET_IMPORTS.REG_CA-RF_190-ALL.M                  Imports of all grades of crude oil from Canada (Region) to HUNT REFINING CO / TUSCALOOSA / AL (190), Monthly                                                                                                                                     CAN     USA-AL           RF_190
PET_IMPORTS.REG_CA-RF_225-ALL.M       Imports of all grades of crude oil from Canada (Region) to EXXONMOBIL REFINING & SPLY CO / BEAUMONT / TX (225), Monthly                                                                                                                                     CAN     USA-TX           RF_225

--- RS_ ---
                     series_id                                                                                         name geography geography2 destination_code
PET_IMPORTS.REG_CA-RS_KY-ALL.M   Imports of all grades of crude oil from Canada (Region) to refineries in Kentucky, Monthly       CAN     USA-KY            RS_KY
PET_IMPORTS.REG_CA-RS_MI-ALL.M   Imports of all grades of crude oil from Canada (Region) to refineries in Michigan, Monthly       CAN     USA-MI            RS_MI
PET_IMPORTS.REG_CA-RS_UT-ALL.M       Imports of all grades of crude oil from Canada (Region) to refineries in Utah, Monthly       CAN     USA-UT            RS_UT
PET_IMPORTS.REG_CA-RS_OK-ALL.M   Imports of all grades of crude oil from Canada (Region) to refineries in Oklahoma, Monthly       CAN     USA-OK            RS_OK
PET_IMPORTS.REG_CA-RS_AL-ALL.M    Imports of all grades of crude oil from Canada (Region) to refineries in Alabama, Monthly       CAN     USA-AL            RS_AL
PET_IMPORTS.REG_CA-RS_WA-ALL.M Imports of all grades of crude oil from Canada (Region) to refineries in Washington, Monthly       CAN     USA-WA            RS_WA
PET_IMPORTS.REG_CA-RS_NJ-ALL.M Imports of all grades of crude oil from Canada (Region) to refineries in New Jersey, Monthly       CAN     USA-NJ            RS_NJ
PET_IMPORTS.REG_CA-RS_IN-ALL.M    Imports of all grades of crude oil from Canada (Region) to refineries in Indiana, Monthly       CAN     USA-IN            RS_IN
PET_IMPORTS.REG_CA-RS_AK-ALL.M     Imports of all grades of crude oil from Canada (Region) to refineries in Alaska, Monthly       CAN     USA-AK            RS_AK
PET_IMPORTS.REG_CA-RS_CO-ALL.M   Imports of all grades of crude oil from Canada (Region) to refineries in Colorado, Monthly       CAN     USA-CO            RS_CO

--- PT_ ---
                       series_id                                                                       name                                                                                                                                                                            geography geography2 destination_code
PET_IMPORTS.REG_EU-PT_2001-ALL.M Imports of all grades of crude oil from Europe to Morgan City, LA, Monthly ALB+AUT+BEL+BGR+BIH+CHE+CSK+CYP+CZE+DDR+DEU+DEUW+DNK+ESP+EST+FIN+FRA+FRO+GBR+GIB+GRC+HRV+HUN+IRL+ISL+ITA+LTU+LUX+LVA+MKD+MLT+MNE+NLD+NOR+POL+PRT+ROU+SCG+SRB+SVK+SVN+SWE+TUR+XKS+YUG     USA-LA          PT_2001
 PET_IMPORTS.WORLD-PT_4503-ALL.M     Imports of all grades of crude oil from World to St Louis, MO, Monthly                                                                                                                                                                                  WLD     USA-MO          PT_4503
 PET_IMPORTS.WORLD-PT_5505-ALL.M        Imports of all grades of crude oil from World to Tulsa, OK, Monthly                                                                                                                                                                                  WLD     USA-OK          PT_5505
 PET_IMPORTS.WORLD-PT_5312-ALL.M Imports of all grades of crude oil from World to Corpus Chris, TX, Monthly                                                                                                                                                                                  WLD     USA-TX          PT_5312
 PET_IMPORTS.WORLD-PT_5301-ALL.M      Imports of all grades of crude oil from World to Houston, TX, Monthly                                                                                                                                                                                  WLD     USA-TX          PT_5301
PET_IMPORTS.REG_EU-PT_1903-ALL.M  Imports of all grades of crude oil from Europe to Pascagoula, MS, Monthly ALB+AUT+BEL+BGR+BIH+CHE+CSK+CYP+CZE+DDR+DEU+DEUW+DNK+ESP+EST+FIN+FRA+FRO+GBR+GIB+GRC+HRV+HUN+IRL+ISL+ITA+LTU+LUX+LVA+MKD+MLT+MNE+NLD+NOR+POL+PRT+ROU+SCG+SRB+SVK+SVN+SWE+TUR+XKS+YUG     USA-MS          PT_1903
 PET_IMPORTS.WORLD-PT_3802-ALL.M   Imports of all grades of crude oil from World to Port Huron, MI, Monthly                                                                                                                                                                                  WLD     USA-MI          PT_3802
 PET_IMPORTS.WORLD-PT_5306-ALL.M   Imports of all grades of crude oil from World to Texas City, TX, Monthly                                                                                                                                                                                  WLD     USA-TX          PT_5306
 PET_IMPORTS.WORLD-PT_3902-ALL.M       Imports of all grades of crude oil from World to Peoria, IL, Monthly                                                                                                                                                                                  WLD     USA-IL          PT_3902
 PET_IMPORTS.WORLD-PT_3901-ALL.M      Imports of all grades of crude oil from World to Chicago, IL, Monthly                                                                                                                                                                                  WLD     USA-IL          PT_3901

In [7]:
# Create the main Tableau dataset
# Grain: Source Country × Month
# Destination: Total U.S.
# Product: All Grades of crude oil
# Frequency: Monthly
# Source: Country-level

tableau_main = df[
    (df["geography2"] == "USA") &
    (df["series_id"].str.startswith("PET_IMPORTS.CTY_", na=False)) &
    (df["series_id"].str.endswith(".M", na=False)) &
    (df["name"].str.contains(
        "all grades of crude oil",
        case=False,
        na=False
    ))
].copy()

print("Tableau main dataset created.")
print("Rows:", len(tableau_main))
print("Columns:", len(tableau_main.columns))

tableau_main.head()

Tableau main dataset created.
Rows: 5107
Columns: 13

,series_id,name,units,frequency,source,geography,geography2,start,end,last_updated,geoset_id,date,value
44749,PET_IMPORTS.CTY_VE-US-ALL.M,Imports of all grades of crude oil from Venezu...,thousand barrels,NaN,"EIA, U.S. Energy Information Administration",VEN,USA,200901,202607,2026-09-29T19:32:50-04:00,PET_IMPORTS.US-ALL.M,202607,21718
44750,PET_IMPORTS.CTY_VE-US-ALL.M,Imports of all grades of crude oil from Venezu...,thousand barrels,NaN,"EIA, U.S. Energy Information Administration",VEN,USA,200901,202607,2026-09-29T19:32:50-04:00,PET_IMPORTS.US-ALL.M,202606,18913
44751,PET_IMPORTS.CTY_VE-US-ALL.M,Imports of all grades of crude oil from Venezu...,thousand barrels,NaN,"EIA, U.S. Energy Information Administration",VEN,USA,200901,202607,2026-09-29T19:32:50-04:00,PET_IMPORTS.US-ALL.M,202605,14593
44752,PET_IMPORTS.CTY_VE-US-ALL.M,Imports of all grades of crude oil from Venezu...,thousand barrels,NaN,"EIA, U.S. Energy Information Administration",VEN,USA,200901,202607,2026-09-29T19:32:50-04:00,PET_IMPORTS.US-ALL.M,202604,12859
44753,PET_IMPORTS.CTY_VE-US-ALL.M,Imports of all grades of crude oil from Venezu...,thousand barrels,NaN,"EIA, U.S. Energy Information Administration",VEN,USA,200901,202607,2026-09-29T19:32:50-04:00,PET_IMPORTS.US-ALL.M,202603,11578

In [8]:
# Create Tableau-friendly columns

tableau_main = tableau_main.copy()

# -----------------------------
# 1. Rename existing columns
# -----------------------------

tableau_main = tableau_main.rename(
    columns={
        "geography": "Source Country Code",
        "geography2": "Destination Country Code",
        "value": "Import Volume (000 Barrels)",
        "units": "Unit"
    }
)

# -----------------------------
# 2. Create readable country fields
# -----------------------------

country_mapping = {
    "AGO": "Angola",
    "ARE": "United Arab Emirates",
    "ARG": "Argentina",
    "AZE": "Azerbaijan",
    "BRA": "Brazil",
    "CMR": "Cameroon",
    "COG": "Republic of Congo",
    "COL": "Colombia",
    "DZA": "Algeria",
    "ECU": "Ecuador",
    "GAB": "Gabon",
    "GHA": "Ghana",
    "GNQ": "Equatorial Guinea",
    "GTM": "Guatemala",
    "GUY": "Guyana",
    "IDN": "Indonesia",
    "IRQ": "Iraq",
    "KAZ": "Kazakhstan",
    "KWT": "Kuwait",
    "LBY": "Libya",
    "MEX": "Mexico",
    "NGA": "Nigeria",
    "NOR": "Norway",
    "PER": "Peru",
    "RUS": "Russia",
    "SAU": "Saudi Arabia",
    "TCD": "Chad",
    "THA": "Thailand",
    "TTO": "Trinidad and Tobago",
    "VEN": "Venezuela",
    "VNM": "Vietnam",
    "CAN": "Canada",
    "GBR": "United Kingdom"
}

tableau_main["Source Country"] = (
    tableau_main["Source Country Code"]
    .map(country_mapping)
    .fillna(tableau_main["Source Country Code"])
)

# -----------------------------
# 3. Destination
# -----------------------------

tableau_main["Destination Country"] = "USA"

tableau_main["Destination Type"] = "Total U.S."

# -----------------------------
# 4. Crude Grade
# -----------------------------

tableau_main["Crude Grade"] = "All Grades"

# -----------------------------
# 5. Convert YYYYMM to Date
# -----------------------------

tableau_main["Date"] = pd.to_datetime(
    tableau_main["date"].astype(str),
    format="%Y%m"
)

# -----------------------------
# 6. Create time dimensions
# -----------------------------

tableau_main["Year"] = tableau_main["Date"].dt.year

tableau_main["Quarter"] = (
    "Q" + tableau_main["Date"].dt.quarter.astype(str)
)

tableau_main["Month Number"] = (
    tableau_main["Date"].dt.month
)

tableau_main["Month Name"] = (
    tableau_main["Date"].dt.month_name()
)

tableau_main["Year-Month"] = (
    tableau_main["Date"].dt.strftime("%Y-%m")
)

# -----------------------------
# 7. Monthly frequency
# -----------------------------

tableau_main["Frequency"] = "Monthly"

print("Tableau-friendly columns created successfully!")

print("\nColumns:")
print(tableau_main.columns.tolist())

print("\nShape:")
print(tableau_main.shape)

tableau_main.head()

Tableau-friendly columns created successfully!

Columns:
['series_id', 'name', 'Unit', 'frequency', 'source', 'Source Country Code', 'Destination Country Code', 'start', 'end', 'last_updated', 'geoset_id', 'date', 'Import Volume (000 Barrels)', 'Source Country', 'Destination Country', 'Destination Type', 'Crude Grade', 'Date', 'Year', 'Quarter', 'Month Number', 'Month Name', 'Year-Month', 'Frequency']

Shape:
(5107, 24)

,series_id,name,Unit,frequency,source,Source Country Code,Destination Country Code,start,end,last_updated,...,Destination Country,Destination Type,Crude Grade,Date,Year,Quarter,Month Number,Month Name,Year-Month,Frequency
44749,PET_IMPORTS.CTY_VE-US-ALL.M,Imports of all grades of crude oil from Venezu...,thousand barrels,NaN,"EIA, U.S. Energy Information Administration",VEN,USA,200901,202607,2026-09-29T19:32:50-04:00,...,USA,Total U.S.,All Grades,2026-07-01,2026,Q3,7,July,2026-07,Monthly
44750,PET_IMPORTS.CTY_VE-US-ALL.M,Imports of all grades of crude oil from Venezu...,thousand barrels,NaN,"EIA, U.S. Energy Information Administration",VEN,USA,200901,202607,2026-09-29T19:32:50-04:00,...,USA,Total U.S.,All Grades,2026-06-01,2026,Q2,6,June,2026-06,Monthly
44751,PET_IMPORTS.CTY_VE-US-ALL.M,Imports of all grades of crude oil from Venezu...,thousand barrels,NaN,"EIA, U.S. Energy Information Administration",VEN,USA,200901,202607,2026-09-29T19:32:50-04:00,...,USA,Total U.S.,All Grades,2026-05-01,2026,Q2,5,May,2026-05,Monthly
44752,PET_IMPORTS.CTY_VE-US-ALL.M,Imports of all grades of crude oil from Venezu...,thousand barrels,NaN,"EIA, U.S. Energy Information Administration",VEN,USA,200901,202607,2026-09-29T19:32:50-04:00,...,USA,Total U.S.,All Grades,2026-04-01,2026,Q2,4,April,2026-04,Monthly
44753,PET_IMPORTS.CTY_VE-US-ALL.M,Imports of all grades of crude oil from Venezu...,thousand barrels,NaN,"EIA, U.S. Energy Information Administration",VEN,USA,200901,202607,2026-09-29T19:32:50-04:00,...,USA,Total U.S.,All Grades,2026-03-01,2026,Q1,3,March,2026-03,Monthly

In [9]:
# Create Tableau-friendly columns

tableau_main = tableau_main.copy()

# -----------------------------
# 1. Rename existing columns
# -----------------------------

tableau_main = tableau_main.rename(
    columns={
        "geography": "Source Country Code",
        "geography2": "Destination Country Code",
        "value": "Import Volume (000 Barrels)",
        "units": "Unit"
    }
)

# -----------------------------
# 2. Create readable country fields
# -----------------------------

country_mapping = {
    "AGO": "Angola",
    "ARE": "United Arab Emirates",
    "ARG": "Argentina",
    "AZE": "Azerbaijan",
    "BRA": "Brazil",
    "CMR": "Cameroon",
    "COG": "Republic of Congo",
    "COL": "Colombia",
    "DZA": "Algeria",
    "ECU": "Ecuador",
    "GAB": "Gabon",
    "GHA": "Ghana",
    "GNQ": "Equatorial Guinea",
    "GTM": "Guatemala",
    "GUY": "Guyana",
    "IDN": "Indonesia",
    "IRQ": "Iraq",
    "KAZ": "Kazakhstan",
    "KWT": "Kuwait",
    "LBY": "Libya",
    "MEX": "Mexico",
    "NGA": "Nigeria",
    "NOR": "Norway",
    "PER": "Peru",
    "RUS": "Russia",
    "SAU": "Saudi Arabia",
    "TCD": "Chad",
    "THA": "Thailand",
    "TTO": "Trinidad and Tobago",
    "VEN": "Venezuela",
    "VNM": "Vietnam",
    "CAN": "Canada",
    "GBR": "United Kingdom"
}

tableau_main["Source Country"] = (
    tableau_main["Source Country Code"]
    .map(country_mapping)
    .fillna(tableau_main["Source Country Code"])
)

# -----------------------------
# 3. Destination
# -----------------------------

tableau_main["Destination Country"] = "USA"

tableau_main["Destination Type"] = "Total U.S."

# -----------------------------
# 4. Crude Grade
# -----------------------------

tableau_main["Crude Grade"] = "All Grades"

# -----------------------------
# 5. Convert YYYYMM to Date
# -----------------------------

tableau_main["Date"] = pd.to_datetime(
    tableau_main["date"].astype(str),
    format="%Y%m"
)

# -----------------------------
# 6. Create time dimensions
# -----------------------------

tableau_main["Year"] = tableau_main["Date"].dt.year

tableau_main["Quarter"] = (
    "Q" + tableau_main["Date"].dt.quarter.astype(str)
)

tableau_main["Month Number"] = (
    tableau_main["Date"].dt.month
)

tableau_main["Month Name"] = (
    tableau_main["Date"].dt.month_name()
)

tableau_main["Year-Month"] = (
    tableau_main["Date"].dt.strftime("%Y-%m")
)

# -----------------------------
# 7. Monthly frequency
# -----------------------------

tableau_main["Frequency"] = "Monthly"

print("Tableau-friendly columns created successfully!")

print("\nColumns:")
print(tableau_main.columns.tolist())

print("\nShape:")
print(tableau_main.shape)

tableau_main.head()

Tableau-friendly columns created successfully!

Columns:
['series_id', 'name', 'Unit', 'frequency', 'source', 'Source Country Code', 'Destination Country Code', 'start', 'end', 'last_updated', 'geoset_id', 'date', 'Import Volume (000 Barrels)', 'Source Country', 'Destination Country', 'Destination Type', 'Crude Grade', 'Date', 'Year', 'Quarter', 'Month Number', 'Month Name', 'Year-Month', 'Frequency']

Shape:
(5107, 24)

,series_id,name,Unit,frequency,source,Source Country Code,Destination Country Code,start,end,last_updated,...,Destination Country,Destination Type,Crude Grade,Date,Year,Quarter,Month Number,Month Name,Year-Month,Frequency
44749,PET_IMPORTS.CTY_VE-US-ALL.M,Imports of all grades of crude oil from Venezu...,thousand barrels,NaN,"EIA, U.S. Energy Information Administration",VEN,USA,200901,202607,2026-09-29T19:32:50-04:00,...,USA,Total U.S.,All Grades,2026-07-01,2026,Q3,7,July,2026-07,Monthly
44750,PET_IMPORTS.CTY_VE-US-ALL.M,Imports of all grades of crude oil from Venezu...,thousand barrels,NaN,"EIA, U.S. Energy Information Administration",VEN,USA,200901,202607,2026-09-29T19:32:50-04:00,...,USA,Total U.S.,All Grades,2026-06-01,2026,Q2,6,June,2026-06,Monthly
44751,PET_IMPORTS.CTY_VE-US-ALL.M,Imports of all grades of crude oil from Venezu...,thousand barrels,NaN,"EIA, U.S. Energy Information Administration",VEN,USA,200901,202607,2026-09-29T19:32:50-04:00,...,USA,Total U.S.,All Grades,2026-05-01,2026,Q2,5,May,2026-05,Monthly
44752,PET_IMPORTS.CTY_VE-US-ALL.M,Imports of all grades of crude oil from Venezu...,thousand barrels,NaN,"EIA, U.S. Energy Information Administration",VEN,USA,200901,202607,2026-09-29T19:32:50-04:00,...,USA,Total U.S.,All Grades,2026-04-01,2026,Q2,4,April,2026-04,Monthly
44753,PET_IMPORTS.CTY_VE-US-ALL.M,Imports of all grades of crude oil from Venezu...,thousand barrels,NaN,"EIA, U.S. Energy Information Administration",VEN,USA,200901,202607,2026-09-29T19:32:50-04:00,...,USA,Total U.S.,All Grades,2026-03-01,2026,Q1,3,March,2026-03,Monthly

In [10]:
# ============================================================
# FINAL DATA QUALITY VALIDATION
# ============================================================

print("=" * 70)
print("1. DATASET SHAPE")
print("=" * 70)
print("Rows:", len(tableau_main))
print("Columns:", len(tableau_main.columns))


# ------------------------------------------------------------
# 2. MISSING VALUES IN IMPORTANT TABLEAU FIELDS
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("2. MISSING VALUES")
print("=" * 70)

important_columns = [
    "Source Country",
    "Destination Country",
    "Destination Type",
    "Crude Grade",
    "Import Volume (000 Barrels)",
    "Date",
    "Year",
    "Quarter",
    "Month Number",
    "Month Name",
    "Year-Month",
    "Frequency"
]

print(
    tableau_main[important_columns]
    .isnull()
    .sum()
    .to_string()
)


# ------------------------------------------------------------
# 3. DUPLICATE CHECK
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("3. DUPLICATE CHECK")
print("=" * 70)

duplicates = tableau_main.duplicated(
    subset=[
        "Source Country",
        "Date",
        "Crude Grade",
        "Destination Type"
    ]
).sum()

print("Duplicate country-month records:", duplicates)


# ------------------------------------------------------------
# 4. DATE VALIDATION
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("4. DATE VALIDATION")
print("=" * 70)

print("Minimum Date:", tableau_main["Date"].min())
print("Maximum Date:", tableau_main["Date"].max())

print(
    "Invalid dates:",
    tableau_main["Date"].isna().sum()
)


# ------------------------------------------------------------
# 5. SOURCE COUNTRY CHECK
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("5. SOURCE COUNTRY CHECK")
print("=" * 70)

print(
    "Number of source countries:",
    tableau_main["Source Country"].nunique()
)

print("\nSource countries:")
print(
    sorted(
        tableau_main["Source Country"].unique()
    )
)


# ------------------------------------------------------------
# 6. DESTINATION CHECK
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("6. DESTINATION CHECK")
print("=" * 70)

print(
    tableau_main[
        [
            "Destination Country",
            "Destination Type",
            "Crude Grade",
            "Frequency"
        ]
    ]
    .drop_duplicates()
    .to_string(index=False)
)


# ------------------------------------------------------------
# 7. IMPORT VOLUME VALIDATION
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("7. IMPORT VOLUME VALIDATION")
print("=" * 70)

print(
    tableau_main["Import Volume (000 Barrels)"]
    .describe()
)


# ------------------------------------------------------------
# 8. DATA TYPES AFTER CLEANING
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("8. FINAL DATA TYPES")
print("=" * 70)

print(
    tableau_main[important_columns]
    .dtypes
)

======================================================================
1. DATASET SHAPE
======================================================================
Rows: 5107
Columns: 24

======================================================================
2. MISSING VALUES
======================================================================
Source Country                 0
Destination Country            0
Destination Type               0
Crude Grade                    0
Import Volume (000 Barrels)    0
Date                           0
Year                           0
Quarter                        0
Month Number                   0
Month Name                     0
Year-Month                     0
Frequency                      0

======================================================================
3. DUPLICATE CHECK
======================================================================
Duplicate country-month records: 0

======================================================================
4. DATE VALIDATION
======================================================================
Minimum Date: 2009-01-01 00:00:00
Maximum Date: 2026-07-01 00:00:00
Invalid dates: 0

======================================================================
5. SOURCE COUNTRY CHECK
======================================================================
Number of source countries: 61

Source countries:
['ALB', 'AUS', 'Algeria', 'Angola', 'Argentina', 'Azerbaijan', 'BHS', 'BLZ', 'BOL', 'BRB', 'BRN', 'Brazil', 'CHN', 'CIV', 'COD', 'Cameroon', 'Canada', 'Chad', 'Colombia', 'DNK', 'EGY', 'ESP', 'Ecuador', 'Equatorial Guinea', 'Gabon', 'Ghana', 'Guatemala', 'Guyana', 'IRN', 'ITA', 'Indonesia', 'Iraq', 'Kazakhstan', 'Kuwait', 'Libya', 'MRT', 'MYS', 'Mexico', 'NLD', 'Nigeria', 'Norway', 'OMN', 'PAN', 'PNG', 'Peru', 'QAT', 'Republic of Congo', 'Russia', 'SEN', 'SSD', 'SYR', 'Saudi Arabia', 'TUN', 'Thailand', 'Trinidad and Tobago', 'United Arab Emirates', 'United Kingdom', 'Venezuela', 'Vietnam', 'YEM', 'ZAF']

======================================================================
6. DESTINATION CHECK
======================================================================
Destination Country Destination Type Crude Grade Frequency
                USA       Total U.S.  All Grades   Monthly

======================================================================
7. IMPORT VOLUME VALIDATION
======================================================================
count      5107.000000
mean       9328.757392
std       20602.042373
min           1.000000
25%         717.500000
50%        2070.000000
75%        7467.500000
max      135354.000000
Name: Import Volume (000 Barrels), dtype: float64

======================================================================
8. FINAL DATA TYPES
======================================================================
Source Country                            str
Destination Country                       str
Destination Type                          str
Crude Grade                               str
Import Volume (000 Barrels)             int64
Date                           datetime64[us]
Year                                    int32
Quarter                                   str
Month Number                            int32
Month Name                                str
Year-Month                                str
Frequency                                 str
dtype: object

In [11]:
print("Duplicate country-month records:", duplicates)

Duplicate country-month records: 0

In [13]:
# Select final columns for Tableau

tableau_columns = [
    "Source Country",
    "Destination Country",
    "Destination Type",
    "Crude Grade",
    "Import Volume (000 Barrels)",
    "Date",
    "Year",
    "Quarter",
    "Month Number",
    "Month Name",
    "Year-Month",
    "Frequency",
    "series_id",
    "Source Country Code",
    "Destination Country Code",
    "Unit",
    "Source"
]

tableau_final = tableau_main[tableau_columns].copy()

print("Final Tableau dataset created!")
print("Rows:", len(tableau_final))
print("Columns:", len(tableau_final.columns))

tableau_final.head()

KeyError: "['Source'] not in index"

In [14]:
print(tableau_main.columns.tolist())

['series_id', 'name', 'Unit', 'frequency', 'source', 'Source Country Code', 'Destination Country Code', 'start', 'end', 'last_updated', 'geoset_id', 'date', 'Import Volume (000 Barrels)', 'Source Country', 'Destination Country', 'Destination Type', 'Crude Grade', 'Date', 'Year', 'Quarter', 'Month Number', 'Month Name', 'Year-Month', 'Frequency']

In [15]:
# Select final columns for Tableau

tableau_columns = [
    "Source Country",
    "Destination Country",
    "Destination Type",
    "Crude Grade",
    "Import Volume (000 Barrels)",
    "Date",
    "Year",
    "Quarter",
    "Month Number",
    "Month Name",
    "Year-Month",
    "Frequency",
    "series_id",
    "Source Country Code",
    "Destination Country Code",
    "Unit",
    "source"
]

tableau_final = tableau_main[tableau_columns].copy()

print("Final Tableau dataset created!")
print("Rows:", len(tableau_final))
print("Columns:", len(tableau_final.columns))

tableau_final.head()

Final Tableau dataset created!
Rows: 5107
Columns: 17

,Source Country,Destination Country,Destination Type,Crude Grade,Import Volume (000 Barrels),Date,Year,Quarter,Month Number,Month Name,Year-Month,Frequency,series_id,Source Country Code,Destination Country Code,Unit,source
44749,Venezuela,USA,Total U.S.,All Grades,21718,2026-07-01,2026,Q3,7,July,2026-07,Monthly,PET_IMPORTS.CTY_VE-US-ALL.M,VEN,USA,thousand barrels,"EIA, U.S. Energy Information Administration"
44750,Venezuela,USA,Total U.S.,All Grades,18913,2026-06-01,2026,Q2,6,June,2026-06,Monthly,PET_IMPORTS.CTY_VE-US-ALL.M,VEN,USA,thousand barrels,"EIA, U.S. Energy Information Administration"
44751,Venezuela,USA,Total U.S.,All Grades,14593,2026-05-01,2026,Q2,5,May,2026-05,Monthly,PET_IMPORTS.CTY_VE-US-ALL.M,VEN,USA,thousand barrels,"EIA, U.S. Energy Information Administration"
44752,Venezuela,USA,Total U.S.,All Grades,12859,2026-04-01,2026,Q2,4,April,2026-04,Monthly,PET_IMPORTS.CTY_VE-US-ALL.M,VEN,USA,thousand barrels,"EIA, U.S. Energy Information Administration"
44753,Venezuela,USA,Total U.S.,All Grades,11578,2026-03-01,2026,Q1,3,March,2026-03,Monthly,PET_IMPORTS.CTY_VE-US-ALL.M,VEN,USA,thousand barrels,"EIA, U.S. Energy Information Administration"

In [16]:
# Save the final Tableau dataset

output_file = r"D:\MBA\Project data\Petroleum_Import_Forecasting\data\crude_import_tableau_dataset.csv"

tableau_final.to_csv(output_file, index=False)

print("Tableau dataset saved successfully!")
print("File:", output_file)

Tableau dataset saved successfully!
File: D:\MBA\Project data\Petroleum_Import_Forecasting\data\crude_import_tableau_dataset.csv